package io.primer.android.payments.core.errors.data.exception

internal class PaymentResumeException(override val cause: Throwable?) : Exception()
